### PR TITLE
Add support for docker

### PR DESCRIPTION
**Pull request by nunorafaelrocha**
This PR adds support for using Docker by adding the `Dockerfile` and  `.dockerignore` necessary to build images of the application.

It was also necessary to add support for using environment variables to configure the application and to add the missing dependency `mysql` to package.json.

### CODE REVIEW

**Comment by vpp** [comment]
Hi @nunorafaelrocha! Thank you for you PR ,much appreciated.

Looks like it needs to have some tweaks as currently the app does not start with default settings in fresh checkout... It requires msql server running.

I will play and see what is missing.

**Comment by nunorafaelrocha** [comment]
Hi @vpp,

We can use docker compose to run the application container and a mysql container. If you need I can provide an example.

Anyway, you can still use sqlite if you prefer since default settings can be overridden using environment variables - support added on this PR as well.

```sh
docker run --rm -e production_dialect=sqlite -e production_storage="./db.sqlite" -p3000:3000 timeoff
```

When using this solution it's a good idea to expose the storage volume used for sqlite database.

**Comment by nunorafaelrocha** [comment]
Hi @vpp 

Any news on this one? Do you want me to provide any other information?

**Comment by vpp** [comment]
Hi @nunorafaelrocha,

Well.. I am happy to merge them if tests pass on fresh default repo checkout.

If I am able to clone the patched branch and "npm test" produce successful run, I am happy with this.

**Comment by masterkorp** [comment]
Any update about this?

Docker support would be nice.

**Comment by nunorafaelrocha** [comment]
Guessing no one is interested in this given it was open back in 2016... closing the PR.

**Comment by alfredopalhares** [comment]
gif

**Pull request closed without merging**
