### PR TITLE
Exposed color support to the gui. 

### PR DESCRIPTION
**Pull request by djmeuleman**
Exposed color support to the gui. It is working in the team view and the calendar views. 

Still to do (for someone else):
- Replace the input text field for color codes in the admin panel by a color picker
- The color insertion on the model is currently implemented in two places. This should be just one. Couldn't find where though.
- Bug: once you add a new leave type, the colors of all the leave types are reset to #f1f1f1

### CODE REVIEW

**Comment by vpp** [comment]
thank you @djmeuleman

**Comment by marct83** [comment]
Ive tried these changes. Team view Calendar alignment is strange. The Half day coloring is also broken in the employee calendar and Team View Calendar.

**Comment by vpp** [comment]
@marct83 the branch is out of date but it contain the idea of implementation thanks to @djmeuleman 

I am planing to visit that branch and bring the feature into master soon and it is one of the most frequently asked features for cloud hosted version of the app.

**Comment by vpp** [comment]
The pull request was used for inspiration for ¢108

Closing this PR.

**Pull request closed without merging**
