### PR TITLE
Add domain option

### PR DESCRIPTION
**Pull request by nunorafaelrocha**
This adds an option that allows to configure the application domain that will be used on the email templates.

### CODE REVIEW

**Comment by vpp** [comment]
Hi @nunorafaelrocha! Thank you for the patch. 

I really like it, though it conflicts little bit with the way how the app is deployed on timeoff.management (the app is sitting on app.timeoff.management and promotion page is on timeof.management). But this is issue with my infrastructure rather then the application itself and your patch is absolutely fine. I am going to merge it little bit later as I need some tome to sort my infrastructure first.

**Comment by nunorafaelrocha** [comment]
@vpp the default domain remains `timeoff.management`, this PR only allows to configure a domain other than that and will not influence your infrastructure.

**Comment by vpp** [comment]
@nunorafaelrocha, this is line I am worrying abouthttps://github.com/timeoff-management/application/pull/80/files#diff-e70e9fbb6c6dc40e77a58ee09116078cL17

But TBH the more I am thinking about it the more it is important.

**Comment by vpp** [comment]
This pull request was used as a basis for following update:

https://github.com/timeoff-management/application/commit/4cc345df8d953a6c2eb27cdddd12239d2d4c683a

Thank you @nunorafaelrocha for inspiration.

**Pull request closed without merging**
