### PR TITLE
Team view absence summary

### PR DESCRIPTION
**Pull request by petrvecera**
Looks like https://github.com/timeoff-management/application/issues/184#issuecomment-341273802

@vpp I never worked with the libraries you are using in this project. So most likely I haven't made the best implementation. 

So if you could do a code review,  let me know any changes you propose. 

I am about to run the tests now

### CODE REVIEW

**Comment by petrvecera** [comment]
Added commit which fixes the CSS selectors in the tests. 

All tests are green:
image

**Comment by petrvecera** [comment]
So I wanted to add feature for export and I realized that I implemented this poorly.  Much more robust implementation is needed. 

`Absence_awere.js` aka each user has now new function `promise_my_leave_summary_for_month`  which takes a month a returns leave summary for given month. 

The summary is object which looks like this:
image
The keys are leave_type id.

But to implement this feature I needed to improve `promise_my_leaves_for_calendar` to also be able to filter `months`.

This also required to improve `get_deducted_days` to be able to filter by months. 

I also needed to add new function to `company_aware.js` which returns me the company which has leave_types and bank_holidays. This info is required in the company object which user needs to have in the get_deducted_days function to work. I did not found different function which would populate both these fields for me. 

All tests a green.

**Comment by vpp** [comment]
Hi @petrvecera 

Thank you for PR.

I've pulled it into separate pranch for now - *tom-184__petrvecera-team_view_absence_summary*.

Yuo've done great job for this feature.

But the part of the app your have built upon is poorly designed in first place so I have to do some more tweaks before merging your patch into master. I think it is better to do for me rather then moving PR back and forward between us in code review phase.

I have some tome today to do this so hopefully will merge the patch soon.

**Comment by vpp** [comment]
Hi @petrvecera it appeared that the patch from this causes few issues for accounts that have quite a few employees (those around 100 and more): there is DB performance price; and also there is a case when holidays span multiple months - each month should have corresponding deducted amount.

To address those issues I cherry picked some of your ideas into **tom-184__vpp__team_view_absence_summary** branch and adopt them to avoid mentioned issues.

I moved statistic calculation to team view because underlaying code needs to be redesigned to be more flexible (I am planning to refactor it it near future) so that layer to stay at least as it is.

The branch is still in progress: there are tests to be finished.

The company/department summary I think will be moved into separate report page, because having 80-100 employees summary in pop-up model looks like not the best UX.

@petrvecera please do not be discouraged, I really appreciate your help and ideas, it just happened that the big part of the app was written in hurry to make it work and now it takes its toll when one wants to amend it.

**Comment by petrvecera** [comment]
Yeah I understand. When I was getting trough the code I had the feeling that it will put quite a load on the back-end.  
> poorly designed in first place

Yep it looks like there are duplicated things loaded from the DB multiple times

**Comment by vpp** [comment]
I am going to close this PR as based on this the feature was added as part of https://github.com/timeoff-management/application/releases/tag/v0.8.0 release. Which was done based on @petrvecera's work.

Also new ticker #198 was created to incorporate idea from this PR for adding summary.

**Pull request closed without merging**
